export enum TEST_NET_ACTION_TYPES {
  GET_DATA_REQUESTED = "GET_DATA_REQUESTED",
  GET_DATA_RECEIVED = "GET_DATA_RECEIVED",
  GET_DATA_ERROR = "GET_DATA_ERROR",
  SORT_LIST = "SORT_LIST",
  FILTER_LIST = "FILTER_LIST",
  SET_SORTED_AND_FILTRED_LIST = "SET_SORTED_AND_FILTRED_LIST",
}
